### ISSUE TITLE
`\}` in URL generates error message to the application...

### ISSUE THREAD

**Issue by BenjamenMeyer** [painterjd/stoplight#12]
```bash
$ curl 'localhost:8081/myendpoint/\}'
```
generates

```
[] - [] - [2018/04/04 17:07:48] - [myproj_api.api.handlers.generic] - [ERROR] - Unhandled Exception
Traceback (most recent call last):
  File "/home/devuser/code/myproj/.venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devuser/code/myproj/.venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/devuser/code/myproj/.venv/lib/python3.5/site-packages/stoplight/decorators.py", line 144, in wrapper
    if _apply_rule(f, rule, param, getval) is not None:
  File "/home/devuser/code/myproj/.venv/lib/python3.5/site-packages/stoplight/decorators.py", line 40, in _apply_rule
    resp = rule.vfunc(value)
  File "/home/devuser/code/myproj/.venv/lib/python3.5/site-packages/stoplight/decorators.py", line 173, in wrapper
    func(value)
  File "/home/devuser/code/myproj/myproj_api/api/validation/validators.py", line 39, in validate_id
    raise ValidationFailed('Invalid ID {0}'.format(value))
  File "/home/devuser/code/myproj/.venv/lib/python3.5/site-packages/stoplight/exceptions.py", line 7, in __init__
    msg = msg.format(*args, **kwargs)
ValueError: Single '}' encountered in format string
```

Applying the following diff can reproduce in the unit tests:
```diff
diff --git a/stoplight/tests/test_validation.py b/stoplight/tests/test_validation.py
index 6fb6121..0b78c76 100644
--- a/stoplight/tests/test_validation.py
+++ b/stoplight/tests/test_validation.py
@@ -347,7 +347,8 @@ class TestValidationDecorator(TestCase):
         negative_cases = [
             'z', 'y', 'z',
             'ww', 'vv', 'uu',
-            'serial', 'cereal', 'surreal'
+            'serial', 'cereal', 'surreal',
+            '\}', '\{'
         ]
 
         for case in positive_cases:
```
as demonstrated with `tox` here:
```bash
bmeyer@bmeyer:~/Development/other/stoplight$ tox -e py27
GLOB sdist-make: /home/bmeyer/Development/other/stoplight/setup.py
py27 inst-nodeps: /home/bmeyer/Development/other/stoplight/.tox/dist/stoplight-1.2.0.zip
py27 installed: coverage==4.5.1,extras==1.0.0,fixtures==3.0.0,linecache2==1.0.0,nose==1.3.7,pbr==4.0.1,pep8==1.7.1,python-mimeparse==1.6.0,six==1.11.0,stoplight==1.2.0,testtools==2.3.0,traceback2==1.4.0,unittest2==1.1.0
py27 runtests: PYTHONHASHSEED='1507695569'
py27 runtests: commands[0] | nosetests
ERROR: Dispatch function threw an exception.Bad callbackERROR: Dispatch function threw an exception.Bad callbackERROR: Dispatch function threw an exception.Bad callback.....F.......
======================================================================
FAIL: test_function_style_validation (stoplight.tests.test_validation.TestValidationDecorator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bmeyer/Development/other/stoplight/stoplight/tests/test_validation.py", line 359, in test_function_style_validation
    FunctionValidation(case)
AssertionError: RuntimeError not raised

Name                                 Stmts   Miss Branch BrPart  Cover
----------------------------------------------------------------------
stoplight/__init__.py                   62      0      4      0   100%
stoplight/decorators.py                 87      0     30      0   100%
stoplight/exceptions.py                  8      0      0      0   100%
stoplight/rule.py                       21      0      2      0   100%
stoplight/tests/__init__.py              0      0      0      0   100%
stoplight/tests/test_validation.py     284    284     47      0     0%
----------------------------------------------------------------------
TOTAL                                  462    284     83      0    39%
nose.plugins.cover: ERROR: TOTAL Coverage did not reach minimum required: 100%
ERROR: InvocationError: '/home/bmeyer/Development/other/stoplight/.tox/py27/bin/nosetests'
_________________________________________________________________________________ summary __________________________________________________________________________________
ERROR:   py27: commands failed
```

NOTE: I used `py27` as an easy example, but it fails with the other Python versions in tox too.

**Comment by BenjamenMeyer** [comment]
@painterjd I think we need to add some fuzz capabilities to the test I used to reproduce this. I only added the obvious based on what was reported to me by @pglass on my current project; so not sure what other fields we need to check that way.

**Comment by BenjamenMeyer** [comment]
With the following diff I can show it's not a stoplight issue but a regex issue:
```diff
bmeyer@bmeyer:~/Development/other/stoplight/stoplight$ git diff tests/test_validation.py
diff --git a/stoplight/tests/test_validation.py b/stoplight/tests/test_validation.py
index 6fb6121..0bf1b19 100644
--- a/stoplight/tests/test_validation.py
+++ b/stoplight/tests/test_validation.py
@@ -1,3 +1,4 @@
+import re
 from unittest import TestCase
 
 import threading
@@ -10,13 +11,15 @@ import os
 VALIDATED_STR = 'validated'
 globalctx = threading.local()
 
+IS_UPPER_REGEX=re.compile('^[A-Z]*$')
+
 
 @validation_function
 def is_upper(z):
     """Simple validation function for testing purposes
     that ensures that input is all caps
     """
-    if z.upper() != z:
+    if not IS_UPPER_REGEX.match(z):
         raise ValidationFailed('{0} is not uppercase'.format(z))
 
 
@@ -347,7 +350,8 @@ class TestValidationDecorator(TestCase):
         negative_cases = [
             'z', 'y', 'z',
             'ww', 'vv', 'uu',
-            'serial', 'cereal', 'surreal'
+            'serial', 'cereal', 'surreal',
+            '\}', '\{'
         ]
 
         for case in positive_cases:
```

Closing since it's not specific to `stoplight`.

**Comment by BenjamenMeyer** [comment]
Okay - further investigation does point back to `stoplight` but the issue is easy to resolve with respect to stoplight itself.

In my initial investigation I could repeat it yes but I couldn't do so until I was using the regex engine to do the validation. But that was because of how the old validation worked, not because it was an issue with the regex - the regex version just forced it to be an explicit data set.

The issue is actually with the Exceptions raised by `stoplight` - the `ValidationFailed` and `ValidationProgrammingError` exceptions because they do the `msg = msg.format(*args, **kwargs)` and when `msg` contains a `\{` or `\}` then that line itself raises a `ValueError`.

The solution, IMHO, is to not do the `msg.format()` within the Exception and require the caller to format the string appropriately. The reason is:

- `x = {0}'.format('\{')` works just fine - there is no error until it is processed a second time
- there are multiple methods of formatting the string in Python - not just `str.format()` and this caller might use  a different method
- doing the `msg.format` this way means the caller must use a string that can be formatted with `str.format` and provide arguments to the two Exceptions to do that directly.
- unlike with `logging.debug` wanting to use printf-style formatting instead of `str.format` since the `logging` functionality delays the formatting until the last moment so it's only done if the message is actually logged, there is no added benefit to delaying the formatting so the caller can do it just fine in these cases.

**Comment by BenjamenMeyer** [comment]
This will need #15 to pass travis-ci.
